I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/characters.rpy", line 110, in script
    image card luna = im.scale("images/cards/luna_card.jpg", 420, 420)
  File "game/characters.rpy", line 110, in <module>
    image card luna = im.scale("images/cards/luna_card.jpg", 420, 420)
AttributeError: module 'renpy.display.im' has no attribute 'scale'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/characters.rpy", line 110, in script
    image card luna = im.scale("images/cards/luna_card.jpg", 420, 420)
  File "C:\Users\haikal\Downloads\Software\renpy-8.3.7-sdk\renpy\ast.py", line 933, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\haikal\Downloads\Software\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/characters.rpy", line 110, in <module>
    image card luna = im.scale("images/cards/luna_card.jpg", 420, 420)
AttributeError: module 'renpy.display.im' has no attribute 'scale'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
thelast 1.0
Sun Jul 13 14:36:59 2025
