I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 132, in script call
    call unlock_character("Nara", "Anggota OSIS yang kalem dan berwibawa.", "card nara")
  File "game/script.rpy", line 132, in script call
    call unlock_character("Nara", "Anggota OSIS yang kalem dan berwibawa.", "card nara")
ScriptError: could not find label 'unlock_character'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 132, in script call
    call unlock_character("Nara", "Anggota OSIS yang kalem dan berwibawa.", "card nara")
  File "C:\renpy\renpy-8.3.7-sdk\renpy\ast.py", line 1427, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 132, in script call
    call unlock_character("Nara", "Anggota OSIS yang kalem dan berwibawa.", "card nara")
  File "C:\renpy\renpy-8.3.7-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'unlock_character'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
thelast 1.0
Fri Jun  6 14:15:01 2025
